export type StyleProps = {
    inline?: boolean;
    bRadius?: string;
    opacity?: number;
    theme?: any;
    fontSize?: string;
    fontWeight?: string;
    tDecoration?: string;
    tJustify?: string;
    lSpace?: string;
    lHeight?: string;
    font?: string;
    color?: string;
    wBreak?: string;
    wSpacing?: string;
    wWrap?: string;
    linkColor1?: string;
    linkColor2?: string;
    listStyle?: string;
    listStyleImage?: string;
    listStylePosition?: string;
    listStyleType?: string;
    bgColor?: string;
    bgImage?: string;
    bgSize?: string;
    bgPosition?: string;
    bgAttachment?: string;
    bgOrigin?: string;
    boxShadow?: string;
    textShadow?: string;
    filter?: string;
    bColor?: string;
    bWidth?: string;
    bImage?: string;
    bSpacing?: string;
    bStyle?: string;
    alignSelf?: string;
    alignItems?: string;
    alignContent?: string;
    justifyContent?: string;
    outline?: string;
    cursor?: string;
    content?: string;
    overflow?: string;
    overflowX?: string;
    overflowY?: string;
    display?: string;
    position?: string;
    top?: string;
    right?: string;
    bottom?: string;
    left?: string;
    zIndex?: number;
    p?: string;
    pt?: string;
    py?: string;
    pr?: string;
    px?: string;
    pb?: string;
    pl?: string;
    m?: string;
    mt?: string;
    my?: string;
    mr?: string;
    mx?: string;
    mb?: string;
    ml?: string;
    width?: string;
    height?: string;
    minWidth?: string;
    minHeight?: string;
    maxWidth?: string;
    maxHeight?: string;
    lp?: number;
    tv?: number;
};

export type GridProps = {
    font?: string;
    size?: string | number;
    color?: string;
    lineheight?: number;
    ttransform?: string;
    tdecoration?: string;
    tstyle?: string;
    tweight?: string | number;
    tshadow?: string;
    letterspace?: string | number;
    wordspace?: string | number;
    tadjust?: string | number;
    tstretch?: string | number;
    tunderpos?: string | number;
    tindent?: string | number;
    toverflow?: string | number;
    wordbreak?: string;
    linebreak?: string;
    twrap?: string | number;
    talign?: string;
    p?: string;
    m?: string;
    bg?: string;
    bgimage?: string;
    bgsize?: string;
    bgposition?: string;
    bgattach?: string;
    bgorigin?: string;
    border?: string;
    opacity?: number;
    boxshadow?: string;
    textshadow?: string;
    filter?: string;
    display?: string;
    position?: string;
    top?: number | string;
    right?: number | string;
    bottom?: number | string;
    left?: number | string;
    zindex?: number | string;
    width?: string | number;
    height?: string | number;
    minwidth?: string;
    minheight?: string;
    maxwidth?: string;
    maxheight?: string;
    lstyle?: string;
    inline?: boolean;
    ms?: number;
    lp?: number;
    tv?: number;
};

export type TextProps = {
    font?: string;
    size?: string | number;
    color?: string;
    lineheight?: number;
    ttransform?: string;
    tdecoration?: string;
    tstyle?: string;
    tweight?: string | number;
    bg?: string;
    tshadow?: string;
    letterspace?: string | number;
    wordspace?: string | number;
    tadjust?: string | number;
    tstretch?: string | number;
    tunderpos?: string | number;
    tindent?: string | number;
    toverflow?: string | number;
    wordbreak?: string;
    linebreak?: string;
    twrap?: string | number;
    talign?: string;
    p?: string;
    m?: string;
    bg?: string;
    border?: string;
    opacity?: number;
    boxshadow?: string;
    textshadow?: string;
    filter?: string;
    display?: string;
    position?: string;
    top?: number;
    right?: number;
    bottom?: number;
    left?: number;
    zindex?: number;
};

export type ListProps = {
    lstyle?: string;
    font?: string;
    size?: string | number;
    color?: string;
    lineheight?: number;
    ttransform?: string;
    tdecoration?: string;
    tstyle?: string;
    tweight?: string | number;
    bg?: string;
    tshadow?: string;
    letterspace?: string | number;
    wordspace?: string | number;
    tadjust?: string | number;
    tstretch?: string | number;
    tunderpos?: string | number;
    tindent?: string | number;
    toverflow?: string | number;
    wordbreak?: string;
    linebreak?: string;
    twrap?: string | number;
    talign?: string;
    p?: string;
    m?: string;
    bg?: string;
    border?: string;
    opacity?: number;
    boxshadow?: string;
    textshadow?: string;
    filter?: string;
    display?: string;
    position?: string;
    top?: number;
    right?: number;
    bottom?: number;
    left?: number;
    zindex?: number;
};

export type UnderlineProps = {
    props?: any;
    color?: string;
    bg?: string;
};
